<?php
    $validatePasswordMsg = $this->__(
        'Please enter %s or more characters. Leading or trailing spaces will be ignored.',
        Mage::helper('allbear_pciauth')->getPasswordMinLength()
    );
?>

<script type="text/javascript">
    Validation.addAllThese([
        ['validate-password', '<?php echo addslashes($validatePasswordMsg) ?>', function(v) {
            var pass = v.strip(); /*strip leading and trailing spaces*/
            return !(pass.length > 0 && pass.length < 6);
        }]
    ]);
</script>